### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by Asora7** [Asora7/semester-project-2#11]
**Description:**
Plan the project in GitHub project

**Tasks:**
- [x] make kanban board
- [x] Make issues with descriptions
- [x] size
- [x] start and end date
